// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Automatically generated sidebar (includes category overview)
  // tutorialSidebar: [{ type: "autogenerated", dirName: ".", customProps: {} }],

  // Manually defined sidebar to disable category overview
  tutorialSidebar: [
    "introduction",
    "question-types",
    {
      type: "category",
      label: "Module",
      items: ["module/add-module", "module/export-module"],
    },
    {
      type: "category",
      label: "Fragen",
      items: ["questions/add-question", "questions/edit-question"],
    },
    "question-editor",
    "modes",
    "faq",
  ],
};

module.exports = sidebars;
